spring:
  datasource:
    url: jdbc:h2:file:./data/url-shortener
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

app:
  base-url: http://localhost:8080
